### PR TITLE
template proposal v3

### PR DESCRIPTION
**Pull request by walteraa**
This design proposal uses the following logic:
- `events`: Each event is translated in a generic function in its corresponding cloud provider
    - `service`: the generic service name to this event. e.g.: Storage = S3, Google cloud storage, etc.
    -  `type`: It correspond to the kind of event, it can make us create specifc events in each service.
    - `bucket-name`: Useful only when configuring storage service, is basically the bucket which will be listen.
    - `table`: Useful only when configuring database services. The table which our function is listening to.
    - `topic`: Useful only when configuring publ/sub service. The topic/channel which our funciton is listening to.
    - `cloud-provvider`: The Cloud which the its corresponding event will be trigger and where we will deploy the funciton.

- `triggers`: The trigger functions which will be created by the our customer to be deployed.
    - `name`: The name of the function, it will be used to create the function in the customer infrastructure.
    - `script`: The path script. **#TODO: Will it be normilized? Or will we just check if the script is in the cloud-provider pattern?**
    - `cloud-provider`: Customer Cloud provider where it will be deployed.
    - `white-list`: The list of `events` in the file where this function will be triggered. Only events inside this list will be considered to be triggered.
   - `black-list`: The list of `events` excluded. Only the `events` which aren't in this list, will be considered to be triggered.

### CODE REVIEW

**Comment by celicoo** [comment]
I understand the motivation behind this template proposal, but I don't like it
to be honest. We should be focusing on *readability* and *explicitness* instead
of trying to reinvent the wheel.

Just to look to the template, I have to think a lot to understand (dumps down readability)

* What is kind?
* What is metadata?
* What is the meaning of spec? Why does it have this name?

I can see that you are trying to promote composition, but you are thinking backward
and forcing the user to do the same by automatically inheriting all events in all "triggers",
and blacklisting the ones that he doesn't want to inherit. Composition should be the opposite,
by giving freedom to the user to define what he wants (dumps up *explicitness*).

The idea of defining cloud provider and using generic names like "storage" doesn't make me happy (dumps down *explicitness*)
What are we going to do if the service "storage" doesn't exist in all providers that we are going to support? Instead
we should avoid the name provider and work only with services:

* aws-lambda
* azure-function
* google-function

It's going to be easier to maintain and promotes readability and explicitness.

All cloud providers have the concept of a resource, and that's a well know and clear concept for all cloud users.
Because of that, we should be using resources as the top level object to define, well... a resource. In my proposal, we can see
that in action:


```yaml
namespace: name-of-app

resources:
  - aws-lambda:
        handler: path/to/handler
        configurations:
              name: aws-lambda
              runtime: nodejs6.10
              events:
              - http:
                path: users/create
                method: get
              - s3: name-of-bucket
              - schedule: rate(10 minutes)
              - sns: greeter-topic
              - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
              - alexa-skill: amzn1.ask.skill.xx-xx-xx-xx
              - alexa-smart-home: amzn1.ask.skill.xx-xx-xx-xx
              - iot:
                sql: "SELECT * FROM 'some_topic'"
              - cloud-watch-event:
                event:
                  source:
                    - "aws.ec2"
                  detail-type:
                    - "EC2 Instance State-change Notification"
                  detail:
                    state:
                      - pending
              - cloud-watch-log: "/aws/lambda/hello"
              - cognito-user-pool:
                pool: MyUserPool
                trigger: PreSignUp
```

IMHO that's the perfect approach and we should be focusing on improving it. It's easier to understand, on the first look it's possible to understand what resource we are defining, and it's configurations.

**Comment by celicoo** [comment]
@walteraa Hei! Could you please:

* change your commit message to use [Semantic Commit Message](https://seesparkbox.com/foundry/semantic_commit_messages)
* change the name of the file to `puppeteer-draw3.yml`

**Comment by walteraa** [comment]
There's no topic defined to this kind of commits in the Semantic you send, but I can change it to `proposal`.

**Comment by walteraa** [comment]
I am using the best approaches of yaml configuration used in the market(e.g.: Kubernetes, Ansible, terraform, etc) which are great project having massive usage.

As a long-date cloud user, I can ensure you that this patter is very readable, once the variable was good defined. 

Kind is the kind of resource, once the cloud service could have a lot of resource, we should define what this yaml file is referring to. 

Well, metadata is clear, I think any person in IT area should know what metadata means.

Spec is short for specifications. 

About explicitness, it doesn't look good when you are trying to do something generic, define some things in an explicit way should make it verborragic(as I can identify in your proposal) and not generic.

In my opinion, you shouldn't combine what is key and what is value, it is a very bad semantic.

**Pull request merged**
