### PR TITLE
base data structures

### PR DESCRIPTION
**Pull request by 0l0r1n**

### CODE REVIEW

**Comment by celicoo** [comment]
I think what @walteraa means is that we should move the `app` to a `pkg` directory.

**Comment by celicoo** [comment]
@0l0r1n please, rebase your commit and remove the files that are been generated by the build process.

**Comment by celicoo** [comment]
Based on the article [Go Project Layout](https://medium.com/golang-learn/go-project-layout-e5213cdcfaa2), I think we should move the `config` folder to an `internal` folder, and move the `app` folder to a `pkg` folder. If you agree, I can add the cards to the [project](https://github.com/celicoo/puppeteer/projects/1)

**Comment by 0l0r1n** [comment]
@walteraa moved app/ to pkg/ as suggested

@celicoo removed the build files. I'll add the card to make config an internal folder and will pick up that item next

**Comment by walteraa** [comment]
Awesome!!! :smile:

**Pull request merged**
